### ISSUE TITLE
Intermittent `HTTPClient::KeepAliveDisconnected` errors when creating VMs

### ISSUE THREAD

**Issue by michelleheh** [cloudfoundry-incubator/bosh-vsphere-cpi-release#47]
In our CI pipeline, we frequently seen deploys fail with the following error:

```
Error 100: Unknown CPI error 'Unknown' with message 'HTTPClient::KeepAliveDisconnected: ' in 'create_vm' CPI method
```

The CPI logs show that it failed in file provider:

```
Rescued Unknown: HTTPClient::KeepAliveDisconnected: . backtrace: /var/vcap/packages/vsphere_cpi/vendor/bundle/ruby/2.2.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:795:in `block in parse_header'
/var/vcap/packages/vsphere_cpi_ruby/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
/var/vcap/packages/vsphere_cpi_ruby/lib/ruby/2.2.0/timeout.rb:98:in `call'
/var/vcap/packages/vsphere_cpi_ruby/lib/ruby/2.2.0/timeout.rb:98:in `timeout'
/var/vcap/packages/vsphere_cpi/vendor/bundle/ruby/2.2.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:788:in `parse_header'
/var/vcap/packages/vsphere_cpi/vendor/bundle/ruby/2.2.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:771:in `read_header'
/var/vcap/packages/vsphere_cpi/vendor/bundle/ruby/2.2.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:547:in `get_header'
/var/vcap/packages/vsphere_cpi/vendor/bundle/ruby/2.2.0/gems/httpclient-2.7.1/lib/httpclient.rb:1294:in `do_get_header'
/var/vcap/packages/vsphere_cpi/vendor/bundle/ruby/2.2.0/gems/httpclient-2.7.1/lib/httpclient.rb:1241:in `do_get_block'
/var/vcap/packages/vsphere_cpi/vendor/bundle/ruby/2.2.0/gems/httpclient-2.7.1/lib/httpclient.rb:1021:in `block in do_request'
/var/vcap/packages/vsphere_cpi/vendor/bundle/ruby/2.2.0/gems/httpclient-2.7.1/lib/httpclient.rb:1134:in `rescue in protect_keep_alive_disconnected'
/var/vcap/packages/vsphere_cpi/vendor/bundle/ruby/2.2.0/gems/httpclient-2.7.1/lib/httpclient.rb:1128:in `protect_keep_alive_disconnected'
/var/vcap/packages/vsphere_cpi/vendor/bundle/ruby/2.2.0/gems/httpclient-2.7.1/lib/httpclient.rb:1016:in `do_request'
/var/vcap/packages/vsphere_cpi/vendor/bundle/ruby/2.2.0/gems/httpclient-2.7.1/lib/httpclient.rb:858:in `request'
/var/vcap/packages/vsphere_cpi/vendor/bundle/ruby/2.2.0/gems/httpclient-2.7.1/lib/httpclient.rb:771:in `put'
/var/vcap/packages/vsphere_cpi/lib/cloud/vsphere/base_http_client.rb:74:in `do_request'
/var/vcap/packages/vsphere_cpi/lib/cloud/vsphere/base_http_client.rb:39:in `put'
/var/vcap/packages/vsphere_cpi/lib/cloud/vsphere/file_provider.rb:66:in `block in do_request'
/var/vcap/packages/vsphere_cpi/lib/cloud/vsphere/file_provider.rb:72:in `call'
/var/vcap/packages/vsphere_cpi/lib/cloud/vsphere/file_provider.rb:72:in `block in do_request'
/var/vcap/packages/vsphere_cpi/lib/cloud/vsphere/retryer.rb:9:in `block in try'
/var/vcap/packages/vsphere_cpi/lib/cloud/vsphere/retryer.rb:8:in `times'
/var/vcap/packages/vsphere_cpi/lib/cloud/vsphere/retryer.rb:8:in `try'
/var/vcap/packages/vsphere_cpi/lib/cloud/vsphere/file_provider.rb:71:in `do_request'
/var/vcap/packages/vsphere_cpi/lib/cloud/vsphere/file_provider.rb:32:in `upload_file_to_datastore'
/var/vcap/packages/vsphere_cpi/lib/cloud/vsphere/agent_env.rb:37:in `set_env'
/var/vcap/packages/vsphere_cpi/lib/cloud/vsphere/cloud.rb:754:in `add_disk_to_agent_env'
/var/vcap/packages/vsphere_cpi/lib/cloud/vsphere/cloud.rb:403:in `block in attach_disk'
/var/vcap/packages/vsphere_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_common-1.3262.24.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/vsphere_cpi/lib/cloud/vsphere/cloud.rb:366:in `attach_disk'
/var/vcap/packages/vsphere_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-2.0.5/lib/bosh/cpi/cli.rb:79:in `public_send'
/var/vcap/packages/vsphere_cpi/vendor/bundle/ruby/2.2.0/gems/bosh_cpi-2.0.5/lib/bosh/cpi/cli.rb:79:in `run'
/var/vcap/packages/vsphere_cpi/bin/vsphere_cpi:42:in `<main>'I, [2017-12-19T19:40:42.454284 #10823]  INFO -- [req_id 932491]: Starting attach_disk...
```

We are following up with our vSphere admins to see if there are any networking issues. But we noticed that the CPI already tries to retry on `HTTPClient::KeepAliveDisconnected` error as shown [here](https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/55d1160cfcaca637a066a7ebf7e9ba6b6b4f2515/src/vsphere_cpi/lib/cloud/vsphere/sdk_helpers/retryable_stub_adapter.rb#L34). However, the file provider only retries if it gets a 500 from vSphere as shown [here](https://github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release/blob/55d1160cfcaca637a066a7ebf7e9ba6b6b4f2515/src/vsphere_cpi/lib/cloud/vsphere/file_provider.rb#L71-L83). Should the file provider (or even `base_http_client`) be retrying on the same HTTP errors that the stub adapter retries?

Thanks!
@michelleheh && @ljfranklin

**Comment by michelleheh** [comment]
Or maybe instead of retrying, the KeepAlive timeout setting the CPI uses should be adjusted to match the vSphere API server? It's possible the vSphere API server is closing the KeepAlive connection while the CPI http client expected the connection to still be open.

**Comment by ktchen14** [comment]
A couple of initial thoughts as we investigate this further: This isn't necessarily actually related to the KeepAlive setting on either the server or the client. The relevant code is (from `parse_header` in `session.rb` in `httpclient`:

```ruby
  begin
    initial_line = socket.gets("\n")
    if initial_line.nil?
      close
      raise KeepAliveDisconnected.new(self)
    end
  rescue Errno::ECONNABORTED, Errno::ECONNRESET, Errno::EPIPE, IOError
    # JRuby can raise IOError instead of ECONNRESET for now
    close
    raise KeepAliveDisconnected.new(self, $!)
  end
```

Basically `KeepAliveDisconnected` is raised whenever the server aborts the connection or is unreachable. It seems like the most likely explanation for these errors is some flakiness in the network connection between the CPI and the vCenter.

That being said we should probably improve this logic here (the second element of the list returned by the block is `err`; unless `err` is `nil` the block is retried):

```ruby
  response = @retryer.try do
    resp = make_request.call

    if resp.code == 404 && allow_not_found
      [nil, nil]
    elsif resp.code >= 400
      err = "Could not transfer file '#{url}', received status code '#{resp.code}'"
      @logger.warn(err)
      [nil, err]
    else
      [resp, nil]
    end
  end
```

To not only be more Rubyish but also to handle connection level and socket level errors.

**Comment by ljfranklin** [comment]
> This isn't necessarily actually related to the KeepAlive setting

Good catch. We followed up with our vSphere admins and they noticed that all the disconnect errors were coming from a single ESXI host. They put that host in maintenance mode and the next deploy went fine.

> also to handle connection level and socket level errors.

Sounds great, thanks!

**Comment by yeshwantbabar** [comment]
Seems like this was an issue related to the environment. Closing this for now. Please feel free to reopen it if you notice it again.
